use near_contract_standards::non_fungible_token::metadata::{TokenMetadata};

  pub fn get_metadata_egg(index: u64) -> TokenMetadata {
    match index {
      1 => TokenMetadata {
        title: Some(String::from("Egg #1")),
        description: Some(String::from("The number #1 Egg of Nearmon")),
        media: Some(String::from("QmfS2rSW32pgX1td3PvyHaKhWZGS86r8Xc1vLPFsRfige5")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      2 => TokenMetadata {
        title: Some(String::from("Egg #2")),
        description: Some(String::from("The number #2 Egg of Nearmon")),
        media: Some(String::from("QmPc2nLEUguwf1BnnxyQsRVSBkKSgGidqds2Xo3i3P8jQ5")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      3 => TokenMetadata {
        title: Some(String::from("Egg #3")),
        description: Some(String::from("The number #3 Egg of Nearmon")),
        media: Some(String::from("QmYJ88azhV2m1BqVr3toe2WgrdjpPtSVtweYBwzkRgnHz6")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      4 => TokenMetadata {
        title: Some(String::from("Egg #4")),
        description: Some(String::from("The number #4 Egg of Nearmon")),
        media: Some(String::from("QmTESWgQRsjq5yV7ZK1zKShUHEAtRuSatCVeXSU6cok9oQ")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      5 => TokenMetadata {
        title: Some(String::from("Egg #5")),
        description: Some(String::from("The number #5 Egg of Nearmon")),
        media: Some(String::from("QmS7zCzMDwsAfqfx26FBDF8ERUM7A8GxPjSjpr21aXLajo")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      6 => TokenMetadata {
        title: Some(String::from("Egg #6")),
        description: Some(String::from("The number #6 Egg of Nearmon")),
        media: Some(String::from("QmPJqdEtoC7nkdYRGRhEWUCtV9BQmWKA6SqSxBdReDXoCc")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      7 => TokenMetadata {
        title: Some(String::from("Egg #7")),
        description: Some(String::from("The number #7 Egg of Nearmon")),
        media: Some(String::from("QmNfDJSQdyZF9s58R9ySuwdzjnGXuk65bvjsNG61MvVGSB")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      8 => TokenMetadata {
        title: Some(String::from("Egg #8")),
        description: Some(String::from("The number #8 Egg of Nearmon")),
        media: Some(String::from("QmRRCo2tZDSj84EyBPAwhEchktDHciPnvAD564zQQPLtfp")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      9 => TokenMetadata {
        title: Some(String::from("Egg #9")),
        description: Some(String::from("The number #9 Egg of Nearmon")),
        media: Some(String::from("QmSVucNmme5JfvhpttLbS4tk4xkLNx5W1Lg4vmWcapukES")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      10 => TokenMetadata {
        title: Some(String::from("Egg #10")),
        description: Some(String::from("The number #10 Egg of Nearmon")),
        media: Some(String::from("QmepzDqXhoqYLQVnXA93ALtkUHBzmCwccfEEp9iXmucV1d")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      11 => TokenMetadata {
        title: Some(String::from("Egg #11")),
        description: Some(String::from("The number #11 Egg of Nearmon")),
        media: Some(String::from("QmSVucNmme5JfvhpttLbS4tk4xkLNx5W1Lg4vmWcapukES")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      12 => TokenMetadata {
        title: Some(String::from("Egg #12")),
        description: Some(String::from("The number #12 Egg of Nearmon")),
        media: Some(String::from("QmPgozMYh1YSxiqYQfFzZj6J38CcErjuCWRtXsKZ7ueQvB")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      13 => TokenMetadata {
        title: Some(String::from("Egg #13")),
        description: Some(String::from("The number #13 Egg of Nearmon")),
        media: Some(String::from("QmTK2FV1iop2cRkUGMLQMH39aYp8cqjQrJWRGK6qCbQ9t5")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      14 => TokenMetadata {
        title: Some(String::from("Egg #14")),
        description: Some(String::from("The number #14 Egg of Nearmon")),
        media: Some(String::from("QmTgNgim1aBNX4WBhuExrqGUhwffGpSib7BpBfjbpUK78K")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      }, 
      15 => TokenMetadata {
        title: Some(String::from("Egg #15")),
        description: Some(String::from("The number #15 Egg of Nearmon")),
        media: Some(String::from("QmPJqdEtoC7nkdYRGRhEWUCtV9BQmWKA6SqSxBdReDXoCc")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      16 => TokenMetadata {
        title: Some(String::from("Egg #16")),
        description: Some(String::from("The number #16 Egg of Nearmon")),
        media: Some(String::from("QmdpQWsbdjwgRgcsUegeyhhxpdByh3ZsLLac73QRLUDcsU")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      _ => TokenMetadata {
        title: Some(String::from("Egg #16")),
        description: Some(String::from("The number #16 Egg of Nearmon")),
        media: Some(String::from("QmdpQWsbdjwgRgcsUegeyhhxpdByh3ZsLLac73QRLUDcsU")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      }
    }
  }

  pub fn get_metadata_monster_1(index: u64) -> TokenMetadata {
    match index {
      1 => TokenMetadata {
        title: Some(String::from("Rookie Fire Dragon")),
        description: Some(String::from("The Rookie Fire Dragon of Nearmon")),
        media: Some(String::from("QmZ72dpMTscB88pTkn2MoDbf38ukmACbQHhbznnNroME54")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      2 => TokenMetadata {
        title: Some(String::from("Rookie Scelus")),
        description: Some(String::from("The Rookie Scelus of Nearmon")),
        media: Some(String::from("QmW5DsFYJC95pxUzcbX6UVZGBaXyhb2AU6yymksdGw6vzG")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      3 => TokenMetadata {
        title: Some(String::from("Rookie Sylene")),
        description: Some(String::from("The Rookie Sylene of Nearmon")),
        media: Some(String::from("QmNxKD8rdNxUkBwJMJvAKdwemBVrpBTV8CZpi8zZRj1DtH")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      4 => TokenMetadata {
        title: Some(String::from("Rookie Aurakyria")),
        description: Some(String::from("The Rookie Aurakyria  of Nearmon")),
        media: Some(String::from("QmSwyo7GZm659jY6V2mkgg1bgwVfdUdBxidBWPxybjRzmN")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      5 => TokenMetadata {
        title: Some(String::from("Rookie Sylene")),
        description: Some(String::from("The Rookie Sylene of Nearmon")),
        media: Some(String::from("QmNxKD8rdNxUkBwJMJvAKdwemBVrpBTV8CZpi8zZRj1DtH")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      6 => TokenMetadata {
        title: Some(String::from("Rookie Antharas")),
        description: Some(String::from("The Rookie Antharas of Nearmon")),
        media: Some(String::from("QmTo7G98HZ6xeeTnqBL27ZREqhRdnpdsWTw9omQVZnWBdG")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      7 => TokenMetadata {
        title: Some(String::from("Rookie Valakas")),
        description: Some(String::from("The Rookie Valakas of Nearmon")),
        media: Some(String::from("QmZCRCWpn5j11zQPjkiEvTU73tae8CyWCpgXebPufFtYGU")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      8 => TokenMetadata {
        title: Some(String::from("Rookie Water Dragon")),
        description: Some(String::from("The Rookie Water Dragon of Nearmon")),
        media: Some(String::from("Qmf6mFw37h5kt3gH5U9jXV3KzJMncYKRyi9rpeYZgLACLB")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      9 => TokenMetadata {
        title: Some(String::from("Rookie Dark Dragon")),
        description: Some(String::from("The Rookie Dark Dragon of Nearmon")),
        media: Some(String::from("QmeRk8Z4YLZWy9a1bBE5qsvAQEMwsQ34ScVA7xdFjgnMW6")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      10 => TokenMetadata {
        title: Some(String::from("Rookie Great Dragon")),
        description: Some(String::from("The Rookie Great Dragon of Nearmon")),
        media: Some(String::from("QmcK5MfgG17CFnnKF1NRzeoTfLctmXqwx2Wabv7KC4w5rM")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      11 => TokenMetadata {
        title: Some(String::from("Rookie Aurakyria")),
        description: Some(String::from("The Rookie Aurakyria  of Nearmon")),
        media: Some(String::from("QmSwyo7GZm659jY6V2mkgg1bgwVfdUdBxidBWPxybjRzmN")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      12 => TokenMetadata {
        title: Some(String::from("Rookie Fafurion")),
        description: Some(String::from("The Rookie Fafurion of Nearmon")),
        media: Some(String::from("QmeBJAAb8CzZeyDDTKpk7611626VDSG5sYgxP9Kf2hjqZJ")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      13 => TokenMetadata {
        title: Some(String::from("Rookie Lightning Dragon")),
        description: Some(String::from("The Rookie Lightning Dragon of Nearmon")),
        media: Some(String::from("QmaBWDkKtezSmHxQ8r9dcMUUBVPTWF9rd9XpsVcxb6fTr6")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      14 => TokenMetadata {
        title: Some(String::from("Rookie Dark Dragon")),
        description: Some(String::from("The Rookie Dark Dragon of Nearmon")),
        media: Some(String::from("QmeRk8Z4YLZWy9a1bBE5qsvAQEMwsQ34ScVA7xdFjgnMW6")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      15 => TokenMetadata {
        title: Some(String::from("Rookie Antharas")),
        description: Some(String::from("The Rookie Antharas of Nearmon")),
        media: Some(String::from("QmTo7G98HZ6xeeTnqBL27ZREqhRdnpdsWTw9omQVZnWBdG")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      16 => TokenMetadata {
        title: Some(String::from("Rookie Earth Dragon")),
        description: Some(String::from("The Rookie Earth Dragon of Nearmon")),
        media: Some(String::from("QmeRk8Z4YLZWy9a1bBE5qsvAQEMwsQ34ScVA7xdFjgnMW6")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      },
      _ => TokenMetadata {
        title: Some(String::from("Rookie Earth Dragon")),
        description: Some(String::from("The Rookie Earth Dragon of Nearmon")),
        media: Some(String::from("QmeRk8Z4YLZWy9a1bBE5qsvAQEMwsQ34ScVA7xdFjgnMW6")),
        media_hash: None,
        copies: Some(1u64),
        issued_at: None,
        expires_at: None,
        starts_at: None,
        updated_at: None,
        extra: None,
        reference: None,
        reference_hash: None,
      }
    }
  }

    pub fn get_metadata_monster_2(index: u64) -> TokenMetadata {
      match index {
        1 => TokenMetadata {
          title: Some(String::from("Ultimate Fire Dragon")),
          description: Some(String::from("The Ultimate Fire Dragon of Nearmon")),
          media: Some(String::from("QmWHLuDPL7CoMGpp4JoCaSXK8EBozT9WhNrT6T48ZuBzG5")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        2 => TokenMetadata {
          title: Some(String::from("Ultimate Scelus")),
          description: Some(String::from("The Ultimate Scelus of Nearmon")),
          media: Some(String::from("QmRv6oc6idHPErbqsV1oZZKbPKuLUMDwfXuZsM6oVH555j")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        3 => TokenMetadata {
          title: Some(String::from("Ultimate Sylene")),
          description: Some(String::from("The Ultimate Sylene of Nearmon")),
          media: Some(String::from("QmehySar1nYD6stUQECLyFhuigedqqTa5N2cXNvTqoV8dm")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        4 => TokenMetadata {
          title: Some(String::from("Ultimate Aurakyria")),
          description: Some(String::from("The Ultimate Aurakyria  of Nearmon")),
          media: Some(String::from("QmTgFgeqePJ3g7c5ZYuTdV2NQWK2YhqFAWkP67HapBmwJG")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        5 => TokenMetadata {
          title: Some(String::from("Ultimate Sylene")),
          description: Some(String::from("The Ultimate Sylene of Nearmon")),
          media: Some(String::from("QmehySar1nYD6stUQECLyFhuigedqqTa5N2cXNvTqoV8dm")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        6 => TokenMetadata {
          title: Some(String::from("Ultimate Antharas")),
          description: Some(String::from("The Ultimate Antharas of Nearmon")),
          media: Some(String::from("QmTBfmoDQCoZ4RV4tpsySWuGGojvaCFvcgADH6TWbNbGTW")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        7 => TokenMetadata {
          title: Some(String::from("Ultimate Valakas")),
          description: Some(String::from("The Ultimate Valakas of Nearmon")),
          media: Some(String::from("QmPEEBRdSa21ptHK2cvuJxpwABmfYoKkJPLrJn4nmP8kai")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        8 => TokenMetadata {
          title: Some(String::from("Ultimate Water Dragon")),
          description: Some(String::from("The Ultimate Water Dragon of Nearmon")),
          media: Some(String::from("QmZbvrfeQsqwab2Vbec2172GBKXjNW1SGPC1gxEga9BiEb")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        9 => TokenMetadata {
          title: Some(String::from("Ultimate Dark Dragon")),
          description: Some(String::from("The Ultimate Dark Dragon of Nearmon")),
          media: Some(String::from("QmXq5ejQRKeQqyqaukU2aP8wUMzwkqFVbkBMPa41YHGrQ3")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        10 => TokenMetadata {
          title: Some(String::from("Ultimate Great Dragon")),
          description: Some(String::from("The Ultimate Great Dragon of Nearmon")),
          media: Some(String::from("Qma48YJavYPwSYa9w2371b9UJ6f3cqJPS1aydpt1ax3LSG")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        11 => TokenMetadata {
          title: Some(String::from("Ultimate Aurakyria")),
          description: Some(String::from("The Ultimate Aurakyria  of Nearmon")),
          media: Some(String::from("QmTgFgeqePJ3g7c5ZYuTdV2NQWK2YhqFAWkP67HapBmwJG")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        12 => TokenMetadata {
          title: Some(String::from("Ultimate Fafurion")),
          description: Some(String::from("The Ultimate Fafurion of Nearmon")),
          media: Some(String::from("QmSxZ4DB44QBmiuoYVxBSGXJKemtpQALUR9M3FzweYynFb")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        13 => TokenMetadata {
          title: Some(String::from("Ultimate Lightning Dragon")),
          description: Some(String::from("The Ultimate Lightning Dragon of Nearmon")),
          media: Some(String::from("QmTaDpjRsVEJgyV5QRjGGieU8Z58Lh7ciB2ZJro8WCWuwh")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        }, 
        14 => TokenMetadata {
          title: Some(String::from("Ultimate Dark Dragon")),
          description: Some(String::from("The Ultimate Dark Dragon of Nearmon")),
          media: Some(String::from("QmXq5ejQRKeQqyqaukU2aP8wUMzwkqFVbkBMPa41YHGrQ3")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        }, 
        15 => TokenMetadata {
          title: Some(String::from("Ultimate Antharas")),
          description: Some(String::from("The Ultimate Antharas of Nearmon")),
          media: Some(String::from("QmTBfmoDQCoZ4RV4tpsySWuGGojvaCFvcgADH6TWbNbGTW")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        16 => TokenMetadata {
          title: Some(String::from("Ultimate Earth Dragon")),
          description: Some(String::from("The Ultimate Earth Dragon of Nearmon")),
          media: Some(String::from("QmZaGBebwWLbEZGKyzUaWTtGC8yqZhnydhzMmaRkCLAfy9")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        _ => TokenMetadata {
          title: Some(String::from("Ultimate Earth Dragon")),
          description: Some(String::from("The Ultimate Earth Dragon of Nearmon")),
          media: Some(String::from("QmZaGBebwWLbEZGKyzUaWTtGC8yqZhnydhzMmaRkCLAfy9")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        }
      }
    }

    pub fn get_metadata_monster_3(index: u64) -> TokenMetadata {
      match index {
        1 => TokenMetadata {
          title: Some(String::from("Champion Fire Dragon")),
          description: Some(String::from("The Champion Fire Dragon of Nearmon")),
          media: Some(String::from("QmWkhALqwP5qZ5XUdr1YDAZn7XTA7ADycQ12fEzgQYrLUU")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        2 => TokenMetadata {
          title: Some(String::from("Champion Scelus")),
          description: Some(String::from("The Champion Scelus of Nearmon")),
          media: Some(String::from("QmPEFfsooLin6YNmG5JDkym3hbYrfPZCXGA67vgiVAv42N")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        3 => TokenMetadata {
          title: Some(String::from("Champion Sylene")),
          description: Some(String::from("The Champion Sylene of Nearmon")),
          media: Some(String::from("QmZDMFfyiizsKU1Q8z6J6TvLkSQtDghMtwcngwfjQBVt3D")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        4 => TokenMetadata {
          title: Some(String::from("Champion Aurakyria")),
          description: Some(String::from("The Champion Aurakyria  of Nearmon")),
          media: Some(String::from("QmcQVRv56oPSVq976pxrUA5eY4DydU8C7vtxgEop3jMCTT")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        5 => TokenMetadata {
          title: Some(String::from("Champion Sylene")),
          description: Some(String::from("The Champion Sylene of Nearmon")),
          media: Some(String::from("QmZDMFfyiizsKU1Q8z6J6TvLkSQtDghMtwcngwfjQBVt3D")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        6 => TokenMetadata {
          title: Some(String::from("Champion Antharas")),
          description: Some(String::from("The Champion Antharas of Nearmon")),
          media: Some(String::from("QmeTig5qYW3TsGvFJxUJz9GivDPYWH9KULXfoZWhGSoSMK")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        7 => TokenMetadata {
          title: Some(String::from("Champion Valakas")),
          description: Some(String::from("The Champion Valakas of Nearmon")),
          media: Some(String::from("QmWtJAsmbVrSMmNV4ygXLLpheZCeJJ9Seov25pxi2dGuL2")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        8 => TokenMetadata {
          title: Some(String::from("Champion Water Dragon")),
          description: Some(String::from("The Champion Water Dragon of Nearmon")),
          media: Some(String::from("QmXn3bvfJPhfpMuujUCBE77zUXrjLRvu7CMNAA54WmKczS")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        9 => TokenMetadata {
          title: Some(String::from("Champion Dark Dragon")),
          description: Some(String::from("The Champion Dark Dragon of Nearmon")),
          media: Some(String::from("QmYycYVRaXSZpcNQ29zWyXJsoV2AW1LuBb5HWijgoJjDhn")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        10 => TokenMetadata {
          title: Some(String::from("Champion Great Dragon")),
          description: Some(String::from("The Champion Great Dragon of Nearmon")),
          media: Some(String::from("QmZAcGy1NPHYaxVa11SMZ3FMfwMBmEvedJFaQZLtQGGomV")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        11 => TokenMetadata {
          title: Some(String::from("Champion Aurakyria")),
          description: Some(String::from("The Champion Aurakyria  of Nearmon")),
          media: Some(String::from("QmcQVRv56oPSVq976pxrUA5eY4DydU8C7vtxgEop3jMCTT")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        12 => TokenMetadata {
          title: Some(String::from("Champion Fafurion")),
          description: Some(String::from("The Champion Fafurion of Nearmon")),
          media: Some(String::from("QmWDxSkLpcj1UDL2vQvCh8aqvdeAWuUMQTYKq3Yu3T2A3g")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        13 => TokenMetadata {
          title: Some(String::from("Champion Lightning Dragon")),
          description: Some(String::from("The Champion Lightning Dragon of Nearmon")),
          media: Some(String::from("QmSBqPngFHSC1hQzzSTV1DEBWdw1YawX7z5w2Gdhd4udW5")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        14 => TokenMetadata {
          title: Some(String::from("Champion Dark Dragon")),
          description: Some(String::from("The Champion Dark Dragon of Nearmon")),
          media: Some(String::from("QmYycYVRaXSZpcNQ29zWyXJsoV2AW1LuBb5HWijgoJjDhn")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        15 => TokenMetadata {
          title: Some(String::from("Champion Antharas")),
          description: Some(String::from("The Champion Antharas of Nearmon")),
          media: Some(String::from("QmeTig5qYW3TsGvFJxUJz9GivDPYWH9KULXfoZWhGSoSMK")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        16 => TokenMetadata {
          title: Some(String::from("Champion Earth Dragon")),
          description: Some(String::from("The Champion Earth Dragon of Nearmon")),
          media: Some(String::from("QmdEA5c71oh4m5nQ8bxoTghTvTHk9YS8ddHR4HQGZvEC4j")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        },
        _ => TokenMetadata {
          title: Some(String::from("Champion Earth Dragon")),
          description: Some(String::from("The Champion Earth Dragon of Nearmon")),
          media: Some(String::from("QmdEA5c71oh4m5nQ8bxoTghTvTHk9YS8ddHR4HQGZvEC4j")),
          media_hash: None,
          copies: Some(1u64),
          issued_at: None,
          expires_at: None,
          starts_at: None,
          updated_at: None,
          extra: None,
          reference: None,
          reference_hash: None,
        }
      }
    }